ns scale fix
openmsa/etsi-mano-java pull request #31
Opened 2022-12-14 13:07 UTC by PrasadhNanjundan05

2022-12-14 13:21 UTC, Vignaudo requested changes

2022-12-14 13:21 UTC, Vignaudo commented on mano-core-api/src/main/java/com/ubiqube/etsi/mano/service/NsScaleStrategyV3.java
> +				.filter(x -> (x.getAspectId() != null && x.getAspectId().equals(aspectId)))
I don't understand this one.
In SOL003 scaling, `asspectId` is mandatory.
Same in SOL001, for the definition of scale levels, and so on ...

2022-12-14 13:21 UTC, Vignaudo commented on nfvo-core/src/main/java/com/ubiqube/etsi/mano/nfvo/notification/vnfind/VnfIndicatorValueChangeNotificationImpl.java
> +			LOG.info("NS Scale {} {} : {} launched", snbsd.getScalingDirection().toString(), nsInstanceId, nsInst);
Why in VNF indicator, we are talking about NS ?

2022-12-14 13:31 UTC, PrasadhNanjundan05 commented on nfvo-core/src/main/java/com/ubiqube/etsi/mano/nfvo/notification/vnfind/VnfIndicatorValueChangeNotificationImpl.java
> +			LOG.info("NS Scale {} {} : {} launched", snbsd.getScalingDirection().toString(), nsInstanceId, nsInst);
probably we will change the class name later,     it is one scheduler that doe both  vnf and ns auto scale.

2022-12-15 08:11 UTC, Vignaudo commented on nfvo-core/src/main/java/com/ubiqube/etsi/mano/nfvo/notification/vnfind/VnfIndicatorValueChangeNotificationImpl.java
> +			LOG.info("NS Scale {} {} : {} launched", snbsd.getScalingDirection().toString(), nsInstanceId, nsInst);
No it's ok, It's just I didn't read the package.

2022-12-15 09:01 UTC, closed without merging