MSA-11833 added conflict message if double time onboarded the same
openmsa/etsi-mano-java pull request #8
Opened 2022-10-11 09:13 UTC by sundarasuganya

Can you please review the code for locking double onboading request

2022-10-11 10:04 UTC, sle38 commented on mano-core-api/src/main/java/com/ubiqube/etsi/mano/service/pkg/vnf/VnfPackageOnboardingImpl.java
> +			throw new ConflictException("THE_VNF_PACKAGE" + vnfPackage.getId() + " is already stared ONBOARDEDING..");
@sundarasuganya @Vignaudo there is a typo here "ONBOARDEDDING", right ?

2022-10-12 09:17 UTC, sundarasuganya commented on mano-core-api/src/main/java/com/ubiqube/etsi/mano/service/pkg/vnf/VnfPackageOnboardingImpl.java
> +			throw new ConflictException("THE_VNF_PACKAGE" + vnfPackage.getId() + " is already stared ONBOARDEDING..");
@sle38 Corrected typo and committed

2022-11-03 08:44 UTC, Vignaudo requested changes

2022-11-03 08:44 UTC, Vignaudo commented on mano-core-api/src/main/java/com/ubiqube/etsi/mano/service/pkg/vnf/VnfPackageOnboardingImpl.java
> +	}
There is a `Constants` file for Handling those kind of problems

2022-11-03 08:44 UTC, Vignaudo commented on mano-core-api/src/main/java/com/ubiqube/etsi/mano/service/pkg/vnf/VnfPackageOnboardingImpl.java
> +		ensureNotProcessing(vnfPpackage);
The problem here, is you are "locking" for a VnfPackage, but for all other onboarding process.

The idea is to prevent double onboarding. So only  packages can be  onboarded only one by one.

2022-11-25 16:28 UTC, merged